// The pipeline: annotated JS -> AssemblyScript -> asc -> wasm + loader.

import { parse } from "acorn";
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { join, dirname, basename, resolve } from "node:path";
import { createRequire } from "node:module";

import { attachDirectives } from "./directives.js";
import { emitKernel, Diag } from "./emit-as.js";

const require_ = createRequire(import.meta.url);

export const DEFAULTS = {
  optimizeLevel: 3,
  shrinkLevel: 0,
  simd: true,
  threads: true,
  initialMemory: 256,
  maximumMemory: 256,
};

/** Find kernels and their directives in one source file. */
export function analyze(source, filename = "input.js") {
  const comments = [];
  const ast = parse(source, {
    ecmaVersion: "latest",
    sourceType: "module",
    locations: true,
    onComment: comments,
  });

  // Only top-level functions can be kernels; a nested one would capture scope,
  // and AssemblyScript has no closures.
  const fns = [];
  for (const node of ast.body) {
    if (node.type === "FunctionDeclaration") fns.push(node);
    else if (node.type === "ExportNamedDeclaration" && node.declaration?.type === "FunctionDeclaration") {
      fns.push(Object.assign(node.declaration, { __exportStart: node.start }));
    }
  }

  // A comment sits before `export function f`, not before `function f`, so both
  // positions are offered when looking the directive up.
  const attached = attachDirectives(comments, fns.map((f) => ({ start: f.__exportStart ?? f.start })));

  const kernels = [];
  for (const fn of fns) {
    const rec = attached.get(fn.__exportStart ?? fn.start);
    if (!rec || !rec.directives.kernel) continue;
    kernels.push({ fn, directives: rec.directives });
  }
  return { ast, comments, kernels, source, filename };
}

/** Generate AssemblyScript for every kernel in a file. */
export function toAssemblyScript(source, filename = "input.js") {
  const { kernels } = analyze(source, filename);
  if (!kernels.length) return null;

  const warnings = [];
  const chunks = [
    `// GENERATED BY smp.js -- do not edit.`,
    `// source: ${filename}`,
    ``,
  ];

  // Kernels may call one another, so every name must be known before emission.
  const knownFns = new Set(kernels.map((k) => k.fn.id.name));
  // Signatures let a call site cast its arguments to the callee's declared
  // parameter types; AssemblyScript will not narrow implicitly.
  const fnSigs = new Map(kernels.map((k) => [k.fn.id.name, {
    params: k.directives.params, returns: k.directives.returns,
  }]));

  for (const k of kernels) {
    for (const tag of k.directives.unknown) {
      warnings.push(`${filename}: unknown directive '@${tag}' on '${k.fn.id.name}' (ignored)`);
    }
    if (k.directives.simd) {
      warnings.push(
        `${filename}: '@simd' on '${k.fn.id.name}' is parsed and checked but not yet lowered to v128 in 0.1.0; ` +
        `scalar code is emitted. See README "Roadmap".`
      );
    }
    const { code } = emitKernel({ ...k, source, filename, knownFns, fnSigs });
    chunks.push(code);
  }

  return { code: chunks.join("\n"), kernels, warnings };
}

function resolveAsc() {
  // Prefer the consumer's own assemblyscript; fall back to ours.
  for (const spec of ["assemblyscript/bin/asc.js", "assemblyscript/asc"]) {
    try { return require_.resolve(spec); } catch { /* keep looking */ }
  }
  return null;
}

/** Invoke asc. Returns { ok, stdout, stderr, argv }. */
export function runAsc(asPath, outWasm, opts = {}) {
  const o = { ...DEFAULTS, ...opts };
  const asc = resolveAsc();
  if (!asc) {
    throw new Error(
      "assemblyscript not found. Install it alongside smp.js:\n  npm i -D assemblyscript"
    );
  }

  const argv = [
    asc, asPath,
    "--outFile", outWasm,
    "--textFile", outWasm.replace(/\.wasm$/, ".wat"),
    "--runtime", "stub",
    "--importMemory",
    "--optimizeLevel", String(o.optimizeLevel),
    "--shrinkLevel", String(o.shrinkLevel),
  ];
  if (o.threads) argv.push("--enable", "threads", "--sharedMemory");
  if (o.simd) argv.push("--enable", "simd");
  if (o.threads) {
    // --sharedMemory requires a declared maximum.
    argv.push("--initialMemory", String(o.initialMemory), "--maximumMemory", String(o.maximumMemory));
  }

  const r = spawnSync(process.execPath, argv, { encoding: "utf8" });
  return { ok: r.status === 0, stdout: r.stdout || "", stderr: r.stderr || "", argv };
}

/** The ES module emitted next to the wasm, so consumers `import` rather than wire it by hand. */
function loaderSource({ wasmFile, kernels, opts }) {
  const names = kernels.map((k) => k.fn.id.name);
  const parallel = kernels.filter((k) => k.directives.parallel).map((k) => k.fn.id.name);
  return `// GENERATED BY smp.js -- do not edit.
import { createModule } from "smp.js/runtime";

export const wasmUrl = new URL("./${wasmFile}", import.meta.url);

export const meta = {
  kernels: ${JSON.stringify(names)},
  parallel: ${JSON.stringify(parallel)},
  memory: { initial: ${opts.initialMemory}, maximum: ${opts.maximumMemory}, shared: ${!!opts.threads} },
};

/**
 * Instantiate the compiled kernels.
 * @param {{ threads?: number }} [options]
 */
export function load(options = {}) {
  return createModule(wasmUrl, meta, options);
}

export default load;
`;
}

/**
 * Compile one file end to end.
 * @returns {{ ok: boolean, outDir: string, wasm: string, loader: string, as: string, warnings: string[], stderr?: string }}
 */
export function compileFile(inputPath, { outDir, ...opts } = {}) {
  const src = readFileSync(inputPath, "utf8");
  const filename = basename(inputPath);
  const o = { ...DEFAULTS, ...opts };

  const result = toAssemblyScript(src, filename);
  if (!result) {
    return { ok: true, skipped: true, warnings: [`${filename}: no @kernel functions found`] };
  }

  const dir = resolve(outDir ?? join(dirname(inputPath), "smp-build"));
  mkdirSync(dir, { recursive: true });

  const stem = filename.replace(/\.[cm]?js$/, "");
  const asPath = join(dir, `${stem}.ts`);
  const wasmPath = join(dir, `${stem}.wasm`);
  const loaderPath = join(dir, `${stem}.js`);

  writeFileSync(asPath, result.code);

  const asc = runAsc(asPath, wasmPath, o);
  if (!asc.ok) {
    return { ok: false, outDir: dir, as: asPath, warnings: result.warnings, stderr: asc.stderr || asc.stdout };
  }

  writeFileSync(loaderPath, loaderSource({ wasmFile: `${stem}.wasm`, kernels: result.kernels, opts: o }));

  return {
    ok: true, outDir: dir, as: asPath, wasm: wasmPath, loader: loaderPath,
    kernels: result.kernels.map((k) => k.fn.id.name),
    warnings: result.warnings,
  };
}

export { Diag };
